
import { type Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLinks } from "@/components/NavLink";
import Link from "next/link";
import { Home } from "lucide-react"


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Clerk Next.js Quickstart",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					{/* Fixed Top Bar */}
					<header className="fixed top-0 left-0 right-0 z-50 bg-background border-b">
						<div className="flex justify-between items-center px-6 h-16">
							{/* Logo/Brand on the left */}
							<Link href={"/"} className="font-semibold text-lg">
								<Home />
							</Link>

							{/* Spacer to push links + auth to the right */}
							<div className="flex items-center gap-20 ml-auto">
								{/* Navigation Links */}
								<div className="flex items-center gap-7">
									<NavLinks />
								</div>

								{/* Auth Buttons / User Avatar */}
								<div className="flex items-center">
									<SignedOut>
										<SignInButton />
										<SignUpButton>
											<button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-5 cursor-pointer hover:bg-[#5639cc] transition">
												Sign Up
											</button>
										</SignUpButton>
									</SignedOut>
									<SignedIn>
										<UserButton
											appearance={{
												elements: {
													avatarBox: "w-10 h-10"
												}
											}}
										/>
									</SignedIn>
								</div>
							</div>
						</div>
					</header>


					{/* Main Content with top padding to account for fixed header */}
					<main className="pt-16 min-h-screen">
						{children}
					</main>
				</body>
			</html>
		</ClerkProvider >
	);
}

