
import { type Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Clerk Next.js Quickstart",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					{/* Fixed Top Bar */}
					<header className="fixed top-0 left-0 right-0 z-50 bg-background border-b">
						<div className="flex justify-between items-center px-6 h-16">
							{/* Logo/Brand (optional) */}
							<Link href={"/"} className="font-semibold text-lg">
								MyApp
							</Link>

							<Link href={"/contacts"} className="font-semibold text-lg">
								Contacts
							</Link>

							<Link href={"/agencies"} className="font-semibold text-lg">
								Agencies
							</Link>

							{/* Auth Buttons */}
							<div className="flex items-center gap-4">
								<SignedOut>
									<SignInButton />
									<SignUpButton>
										<button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-5 cursor-pointer hover:bg-[#5639cc] transition">
											Sign Up
										</button>
									</SignUpButton>
								</SignedOut>
								<SignedIn>
									<UserButton
										// afterSignOutUrl="/"
										appearance={{
											elements: {
												avatarBox: "w-10 h-10"
											}
										}}
									/>
								</SignedIn>
							</div>
						</div>
					</header>

					{/* Main Content with top padding to account for fixed header */}
					<main className="pt-16 min-h-screen">
						{children}
					</main>
				</body>
			</html>
		</ClerkProvider >
	);
}